### ISSUE TITLE
Application expiry has been exceeded

### ISSUE THREAD

**Issue by outer2H** [anacrolix/cove#38]
Hi. I'm using docker (tag:v0.5.1) and  the log shows:
```
cove  | [2024-12-30 10:54:52 +0000 CRT cove main.go:287]
cove  |   msg="Application expiry has been exceeded. Update the application."
cove  | [2024-12-30 10:54:57 +0000 CRT github.com/anacrolix/gostdapp app.go:47]
cove  |   msg="error in main: application expiry exceeded"
```

**Comment by anacrolix** [comment]
That's odd, I don't get this error. I extended the expiry out beyond a year from this release. Can you check the clock on your Docker/system?

**Comment by outer2H** [comment]
system time seems normal and as I understand docker always use host time

```
u@u3:~/app/cove$ sudo docker compose logs -t
cove  | 2025-02-09T12:28:14.014995381Z [2025-02-09 12:28:14 +0000 CRT cove main.go:287]
cove  | 2025-02-09T12:28:14.015077993Z   msg="Application expiry has been exceeded. Update the application."
cove  | 2025-02-09T12:28:19.016943706Z [2025-02-09 12:28:19 +0000 CRT github.com/anacrolix/gostdapp app.go:47]
cove  | 2025-02-09T12:28:19.016957344Z   msg="error in main: application expiry exceeded"
u@u3:~/app/cove$ date
Sun Feb  9 12:35:08 PM UTC 2025
```

Also this is the compose file:
```
services:
    cove:
        container_name: cove
        ports:
            - 8080:8080/tcp # web portal
            - 42069:42069/tcp # torrent port
            - 42069:42069/udp # torrent port
        volumes:
            - ./data:/data  # path to where keep data, persistent
        image: anacrolix/cove:v0.5.1
```
